version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      # Docker images for node
      - image: circleci/node:10.15.3
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      # Install all needed dependencies
      - run:
          name: Installing npm dependencies
          command: npm install
      # Run app commandss
      - run:
          name: Listing Directory
          command: ls -l

      - run:
          name: Interactive
          command: node
          
      # Save the cache for faster builds
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # Save test coverage results
      - store_artifacts:
          path: coverage
          prefix: coverage
   # only run builds when a push on dev branch happens